<?php

use Illuminate\Database\Seeder;

class TipoFondoComercioSeeder extends Seeder {
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        $as = [
            'Aberturas',
            'Agencia',
            'Agencia Comercial',
            'Albergue Transitorio',
            'Almacén',
            'Antigüedades',
            'Art. de Limpieza',
            'Astillero',
            'Autoservicio',
            'Balnearios',
            'Bar',
            'Bazar',
            'Bicicleteria',
            'Bijouteria',
            'Bombonería',
            'Boutique',
            'Bowling',
            'Cabañas',
            'Café Concert',
            'Cafetería',
            'Carnicería',
            'Carpintería',
            'Casa de comidas',
            'Casa de Repuestos',
            'Centro de Copiado',
            'Centro de Estética',
            'Centro Medico',
            'Cerrajería',
            'Cervecería',
            'Churrería',
            'Ciber',
            'Cigarrería',
            'Clínica',
            'Club',
            'Colegio',
            'Comercio',
            'Comp. de Cabañas',
            'Comp. de calzado',
            'Computación',
            'Confitería',
            'Corralón',
            'Cotillón',
            'Criadero',
            'Cuadra',
            'Delivery',
            'Despacho de Pan',
            'Despensa',
            'Dietética',
            'Discoteca',
            'Droguería',
            'Drugstore',
            'Dulcería',
            'Empanadas',
            'Empresa',
            'Escuela',
            'Estación de Servicio',
            'Estacionamiento',
            'Fabrica',
            'Fábrica de Pastas',
            'Fábrica de Tortas',
            'Farmacia',
            'Ferretería',
            'Fiambrería',
            'Florería',
            'Fondo de comercio',
            'Forrajería',
            'Forrajerías',
            'Fotografía',
            'Franquicias',
            'Frigorífico',
            'Frutería',
            'Futbol 5',
            'Garage',
            'Gastronomía',
            'Geriátrico',
            'Gimnasio',
            'Gomería',
            'Granja',
            'Guardamuebles',
            'Guardería',
            'Heladería',
            'Hostel',
            'Hotel',
            'Imprenta',
            'Inmobiliaria',
            'Instituto',
            'Jardín de infantes',
            'Joyería',
            'Juguetería',
            'Kiosco',
            'Laboratorio',
            'Lavadero de Autos',
            'Lavadero de Ropa',
            'Lencería',
            'Librería',
            'Licorería',
            'Locutorio',
            'Lotería',
            'Lubricentro',
            'Marmolería',
            'Marroquinería',
            'MaxiKiosco',
            'Mensajería',
            'Mercería',
            'Mini mercado',
            'Mueblería',
            'Negocio',
            'Óptica',
            'Otros Negocios',
            'Paddle',
            'Panadería',
            'Pancheria',
            'Pañalera',
            'Papelera',
            'Parada de Diarios',
            'Parrilla',
            'Pastelería',
            'Patio Cervecero',
            'Pelotero',
            'Peluquería',
            'Perfumería',
            'Pescadería',
            'Petshop',
            'Pinturería',
            'Pizzería',
            'Polideportivo',
            'Poli rubro',
            'Pollería',
            'Prode',
            'Pub',
            'Quesería',
            'Quiniela',
            'Receptoría',
            'Regalaría',
            'Remiseria',
            'Reparto',
            'Repostería',
            'Restaurant',
            'Restaurante',
            'RestoBar',
            'Rodados',
            'Ropa',
            'Rotisería',
            'Sala de Ensayo',
            'Salón de Belleza',
            'Salón de Eventos',
            'Salón de fiestas',
            'Sanwicheria',
            'Sedería',
            'Solárium',
            'Supermercado',
            'Talabartería',
            'Taller',
            'Taller Mecánico',
            'Teatro',
            'Tintorería',
            'Transporte',
            'Venta de Materiales',
            'Verdulería',
            'Veterinaria',
            'Video Club',
            'Vidriería',
            'Vinoteca',
            'Vivero',
            'Zapatería',
            'Zapatilleria',
            'Zingueria',
        ];

        foreach ($as as $key => $a) {
            \App\TipoFondoComercio::create([
                'idTipoFondoComercio' => $key + 1,
                'descripcion'         => $a,
            ]);
        }

    }
}
