<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateFicha3sTable extends Migration {
    /**
     * Run the migrations_
     *
     * @return void
     */
    public function up() {
        Schema::create('tb_ficha3s', function (Blueprint $table) {
            $table->increments('idFicha3');
            $table->integer('Direccion_Pais_Id1')->unsigned()->nullable();
            $table->integer('Direccion_Provincia_Id1')->unsigned()->nullable();
            $table->integer('Direccion_Partido_Id1')->unsigned()->nullable();
            $table->integer('Direccion_Localidad_Id1')->unsigned()->nullable();
            $table->integer('Direccion_Ciudad_Id1')->unsigned()->nullable();
            $table->integer('Direccion_Barrio_Id1')->unsigned()->nullable();
            $table->integer('Direccion_SubBarrio_Id1')->unsigned()->nullable();
            $table->integer('Direccion_Calle_Id1')->unsigned()->nullable();
            $table->string('Direccion_Nombrecalle')->nullable();
            $table->string('Direccion_Numero')->nullable();
            $table->string('Direccion_Piso')->nullable();
            $table->string('Direccion_Departamento')->nullable();
            $table->string('Direccion_Coordenadas_Latitud')->nullable();
            $table->string('Direccion_Coordenadas_Longitud')->nullable();
            $table->string('AptoCredito')->nullable();
            $table->string('LongitudFrente')->nullable();
            $table->string('LongitudFondo')->nullable();
            $table->string('SuperficieCubierta')->nullable();
            $table->string('SuperficieDescubierta')->nullable();
            $table->string('Antiguedad')->nullable();
            $table->string('AptoProfesional')->nullable();
            $table->string('CantidadCocheras')->nullable();
            $table->string('CocheraOptativa')->nullable();
            $table->string('Disposicion')->nullable();
            $table->string('Expensas')->nullable();
            $table->string('Orientacion')->nullable();
            $table->string('PropiedadOcupada')->nullable();
            $table->string('TipoBalcon')->nullable();
            $table->string('TipoExpensas')->nullable();
            $table->string('TipoVista')->nullable();
            $table->string('TipoCosta')->nullable();
            $table->string('TipoUnidad')->nullable();
            $table->string('Estado')->nullable();
            $table->string('CantidadBanos')->nullable();
            $table->string('CantidadAmbientes')->nullable();
            $table->string('CantidadDormitorios')->nullable();
            $table->string('Ambientes_Altillo')->nullable();
            $table->string('Ambientes_Antesala')->nullable();
            $table->string('Ambientes_Balcon')->nullable();
            $table->string('Ambientes_Bano')->nullable();
            $table->string('Ambientes_Bar')->nullable();
            $table->string('Ambientes_Baulera')->nullable();
            $table->string('Ambientes_Biblioteca')->nullable();
            $table->string('Ambientes_Circulacion')->nullable();
            $table->string('Ambientes_Cochera')->nullable();
            $table->string('Ambientes_Cocina')->nullable();
            $table->string('Ambientes_CocinaComedor')->nullable();
            $table->string('Ambientes_CocinaKitchinette')->nullable();
            $table->string('Ambientes_Comedor')->nullable();
            $table->string('Ambientes_ComedorDiario')->nullable();
            $table->string('Ambientes_CuartoDePlanchar')->nullable();
            $table->string('Ambientes_Dependencia')->nullable();
            $table->string('Ambientes_DependenciaDeServicio')->nullable();
            $table->string('Ambientes_Dormitorio')->nullable();
            $table->string('Ambientes_Entrepiso')->nullable();
            $table->string('Ambientes_Escritorio')->nullable();
            $table->string('Ambientes_Estudio')->nullable();
            $table->string('Ambientes_FamilyRoom')->nullable();
            $table->string('Ambientes_Hall')->nullable();
            $table->string('Ambientes_Jardin')->nullable();
            $table->string('Ambientes_Lavadero')->nullable();
            $table->string('Ambientes_Living')->nullable();
            $table->string('Ambientes_LivingComedor')->nullable();
            $table->string('Ambientes_Palier')->nullable();
            $table->string('Ambientes_Patio')->nullable();
            $table->string('Ambientes_Playroom')->nullable();
            $table->string('Ambientes_Recepcion')->nullable();
            $table->string('Ambientes_Sotano')->nullable();
            $table->string('Ambientes_Suite')->nullable();
            $table->string('Ambientes_Terraza')->nullable();
            $table->string('Ambientes_Toilette')->nullable();
            $table->string('Ambientes_Vestidor')->nullable();
            $table->string('Instalaciones_AguaCaliente')->nullable();
            $table->string('Instalaciones_AguaCalienteCentral')->nullable();
            $table->string('Instalaciones_AguaCorriente')->nullable();
            $table->string('Instalaciones_AireAcondicionadoIndividual')->nullable();
            $table->string('Instalaciones_Amoblado')->nullable();
            $table->string('Instalaciones_Ascensor')->nullable();
            $table->string('Instalaciones_AscensoresDeServicio')->nullable();
            $table->string('Instalaciones_AscensoresPrincipales')->nullable();
            $table->string('Instalaciones_Cable')->nullable();
            $table->string('Instalaciones_CajaFuerte')->nullable();
            $table->string('Instalaciones_Caldera')->nullable();
            $table->string('Instalaciones_Calefaccion')->nullable();
            $table->string('Instalaciones_CanchaFutbol')->nullable();
            $table->string('Instalaciones_CanchaTenis')->nullable();
            $table->string('Instalaciones_Desayunador')->nullable();
            $table->string('Instalaciones_Electricidad')->nullable();
            $table->string('Instalaciones_ExtractorDeAire')->nullable();
            $table->string('Instalaciones_GasEnvasado')->nullable();
            $table->string('Instalaciones_GasNatural')->nullable();
            $table->string('Instalaciones_HogarALena')->nullable();
            $table->string('Instalaciones_InstalacionParrilla')->nullable();
            $table->string('Instalaciones_LosaRadiante')->nullable();
            $table->string('Instalaciones_MueblesDeCocina')->nullable();
            $table->string('Instalaciones_MovilidadReducida')->nullable();
            $table->string('Instalaciones_Pavimento')->nullable();
            $table->string('Instalaciones_Solarium')->nullable();
            $table->string('Instalaciones_Telefono')->nullable();
            $table->string('Instalaciones_Termotanque')->nullable();
            $table->string('Servicios_ABL')->nullable();
            $table->string('Servicios_AguaCorriente')->nullable();
            $table->string('Servicios_Calefaccion')->nullable();
            $table->string('Servicios_Electricidad')->nullable();
            $table->string('Servicios_GasEnvasado')->nullable();
            $table->string('Servicios_GasNatural')->nullable();
            $table->string('Servicios_Internet')->nullable();
            $table->string('Servicios_Limpieza')->nullable();
            $table->string('Servicios_Refrigeracion')->nullable();
            $table->string('Servicios_Rentas')->nullable();
            $table->string('Servicios_RopaCama')->nullable();
            $table->string('Servicios_Seguridad')->nullable();
            $table->string('Servicios_Telefono')->nullable();
            $table->string('Servicios_Toallas')->nullable();
            $table->string('Servicios_Videocable')->nullable();
            $table->string('Servicios_Vigilancia')->nullable();
            $table->string('Generales_PermiteMascotas')->nullable();
            $table->string('Generales_SeguroCaucion')->nullable();
            $table->string('Edificio_TipoEdificio')->nullable();
            $table->string('Edificio_Estado')->nullable();
            $table->string('Edificio_CantidadCocheras')->nullable();
            $table->string('Edificio_PropiedadOcupada')->nullable();
            $table->string('Edificio_Antiguedad')->nullable();
            $table->string('Edificio_DepartamentosPorPiso')->nullable();
            $table->string('Edificio_CantidadPisos')->nullable();
            $table->string('Edificio_SuperficiePlaya')->nullable();
            $table->string('Edificio_SuperficieDeposito')->nullable();
            $table->string('Edificio_LongitudFrente')->nullable();
            $table->string('Edificio_LongitudFondo')->nullable();
            $table->string('Edificio_TipoFrente')->nullable();
            $table->string('Edificio_TipoVista')->nullable();
            $table->string('Edificio_TipoCosta')->nullable();
            $table->string('Edificio_Disponibilidad')->nullable();
            $table->string('Edificio_Servicios_ABL')->nullable();
            $table->string('Edificio_Servicios_AguaCorriente')->nullable();
            $table->string('Edificio_Servicios_Bar')->nullable();
            $table->string('Edificio_Servicios_Calefaccion')->nullable();
            $table->string('Edificio_Servicios_Cocina')->nullable();
            $table->string('Edificio_Servicios_Conmutador')->nullable();
            $table->string('Edificio_Servicios_Electricidad')->nullable();
            $table->string('Edificio_Servicios_GasEnvasado')->nullable();
            $table->string('Edificio_Servicios_GasNatural')->nullable();
            $table->string('Edificio_Servicios_Internet')->nullable();
            $table->string('Edificio_Servicios_Lavanderia')->nullable();
            $table->string('Edificio_Servicios_Refrigeracion')->nullable();
            $table->string('Edificio_Servicios_Rentas')->nullable();
            $table->string('Edificio_Servicios_Seguridad')->nullable();
            $table->string('Edificio_Servicios_Telefono')->nullable();
            $table->string('Edificio_Servicios_Videocable')->nullable();
            $table->string('Edificio_Servicios_Vigilancia')->nullable();
            $table->string('Edificio_Instalaciones_AireAcondicionadoCentral')->nullable();
            $table->string('Edificio_Instalaciones_Ascensor')->nullable();
            $table->string('Edificio_Instalaciones_Caldera')->nullable();
            $table->string('Edificio_Instalaciones_EspacioParaVehiculo')->nullable();
            $table->string('Edificio_Instalaciones_Gimnasio')->nullable();
            $table->string('Edificio_Instalaciones_GrupoElectrogeno')->nullable();
            $table->string('Edificio_Instalaciones_JuegosParaChicos')->nullable();
            $table->string('Edificio_Instalaciones_Laundry')->nullable();
            $table->string('Edificio_Instalaciones_Pileta')->nullable();
            $table->string('Edificio_Instalaciones_SalonDeFiestas')->nullable();
            $table->string('Edificio_Instalaciones_Sauna')->nullable();
            $table->string('Edificio_Instalaciones_Termotanque')->nullable();

            $table->integer('fk_tipoPropiedad')->unsigned()->nullable();
            $table->timestamps();


        });
    }

    /**
     * Reverse the migrations_
     *
     * @return void
     */
    public function down() {
        Schema::dropIfExists('tb_ficha3s');
    }
}
