<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Hotel extends Model {
    use SoftDeletes;
    protected $table      = 'tb_mails';
    protected $primaryKey = 'idMail';

    protected $fillable = [
        'Direccion_Pais_Id1',
        'Direccion_Provincia_Id1',
        'Direccion_Partido_Id1',
        'Direccion_Localidad_Id1',
        'Direccion_Ciudad_Id1',
        'Direccion_Barrio_Id1',
        'Direccion_SubBarrio_Id1',
        'Direccion_Calle_Id1',
        'Direccion_Nombrecalle',
        'Direccion_Numero',
        'Direccion_Piso',
        'Direccion_Departamento',
        'Direccion_Coordenadas_Latitud',
        'Direccion_Coordenadas_Longitud',
        'SuperficieTerreno',
        'SuperficieCubierta',
        'SuperficieDescubierta',
        'SuperficiePlaya',
        'SuperficieDeposito',
        'Antiguedad',
        'CantidadPisos',
        'HabitacionesPorPiso',
        'fk_Estado',
        'CantidadPersonal',
        'RentabilidadAnual',
        'CantidadHabitaciones',
        'CantidadEstrellas',
        'cupada',
        'CantidadPlazas',
        'CantidadCubiertos',
        'fk_TipoHotel',
        'fk_TipoVista',
        'fk_TipoCosta',
        'fk_TipoPendiente',
        'Ambientes_Balcon',
        'Ambientes_Bano',
        'Ambientes_Bar',
        'Ambientes_Biblioteca',
        'Ambientes_Cochera',
        'Ambientes_Deposito',
        'Ambientes_Garage',
        'Ambientes_Jardin',
        'Ambientes_Lavadero',
        'Ambientes_Oficina',
        'Ambientes_Sala',
        'Ambientes_Salon',
        'Ambientes_SalonPublico',
        'Ambientes_Sotano',
        'Ambientes_Vestuario',
        'Servicios_ABL',
        'Servicios_AguaCorriente',
        'Servicios_Bar',
        'Servicios_Calefaccion',
        'Servicios_Cocina',
        'Servicios_Conmutador',
        'Servicios_Electricidad',
        'Servicios_GasEnvasado',
        'Servicios_GasNatural',
        'Servicios_Internet',
        'Servicios_Lavanderia',
        'Servicios_Limpieza',
        'Servicios_Refrigeracion',
        'Servicios_Rentas',
        'Servicios_RopaCama',
        'Servicios_Seguridad',
        'Servicios_Toallas',
        'Servicios_Telefono',
        'Servicios_Videocable',
        'Servicios_Vigilancia',
        'Instalaciones_AguaCaliente',
        'Instalaciones_AguaCorriente',
        'Instalaciones_AireAcondicionadoCentral',
        'Instalaciones_AireAcondicionadoIndividual',
        'Instalaciones_Ascensor',
        'Instalaciones_Gimnasio',
        'Instalaciones_GrupoElectrogeno',
        'Instalaciones_JuegosParaChicos',
        'Instalaciones_Laundry',
        'Instalaciones_Pileta',
        'Instalaciones_Restaurant',
        'Instalaciones_SalonDeFiestas',
        'Instalaciones_Sauna',
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];
}
