<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Local extends Model {
    use SoftDeletes;
    protected $table      = 'tb_mails';
    protected $primaryKey = 'idLocal';

    protected $fillable = [
        'Direccion_Pais_Id1',
        'Direccion_Provincia_Id1',
        'Direccion_Partido_Id1',
        'Direccion_Localidad_Id1',
        'Direccion_Ciudad_Id1',
        'Direccion_Barrio_Id1',
        'Direccion_SubBarrio_Id1',
        'Direccion_Calle_Id1',
        'Direccion_Nombrecalle',
        'Direccion_Numero',
        'Direccion_Piso',
        'Direccion_Departamento',
        'Direccion_Coordenadas_Latitud',
        'Direccion_Coordenadas_Longitud',
        'Antiguedad',
        'fk_Estado',
        'CantidadBanos',
        'fk_TipoLocal',
        'CantidadCocheras',
        'cupada',
        'Vivienda',
        'CantidadPlantas',
        'MontoExpensas',
        'TerrenoPropio',
        'Vidriera',
        'MetrosDeLaEsquina',
        'EnEdificio',
        'UltimaActividad',
        'GaleriaShopping',
        'Ambientes_Altillo',
        'Ambientes_Archivo',
        'Ambientes_Azotea',
        'Ambientes_Balcon',
        'Ambientes_Bano',
        'Ambientes_Bar',
        'Ambientes_Baulera',
        'Ambientes_Cochera',
        'Ambientes_Cocina',
        'Ambientes_Dependencia',
        'Ambientes_DependenciaDeServicio',
        'Ambientes_Deposito',
        'Ambientes_Entrepiso',
        'Ambientes_Galpon',
        'Ambientes_Garage',
        'Ambientes_Jardin',
        'Ambientes_Oficina',
        'Ambientes_Patio',
        'Ambientes_Sala',
        'Ambientes_Sotano',
        'Ambientes_Terraza',
        'Ambientes_Toilette',
        'Ambientes_Vestuario',
        'Servicios_ABL',
        'Servicios_AguaCorriente',
        'Servicios_Bar',
        'Servicios_Conmutador',
        'Servicios_Electricidad',
        'Servicios_GasNatural',
        'Servicios_Internet',
        'Servicios_Limpieza',
        'Servicios_Telefono',
        'Servicios_Videocable',
        'Instalaciones_AguaCaliente',
        'Instalaciones_AguaCalienteCentral',
        'Instalaciones_AguaCloaca',
        'Instalaciones_AguaCorriente',
        'Instalaciones_AguaPozo',
        'Instalaciones_AireAcondicionadoCentral',
        'Instalaciones_AireAcondicionadoIndividual',
        'Instalaciones_AireCaliente',
        'Instalaciones_AscensoresDeServicio',
        'Instalaciones_AscensoresPrincipales',
        'Instalaciones_Boxes',
        'Instalaciones_Caldera',
        'Instalaciones_CajaFuerte',
        'Instalaciones_Calefaccion',
        'Instalaciones_DobleCirculacion',
        'Instalaciones_MovilidadReducida',
        'Instalaciones_Pavimento',
        'Generales_SeguroCaucion',
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

}
