<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Oficina extends Model {
    use SoftDeletes;
    protected $table      = 'tb_oficinas';
    protected $primaryKey = 'idOficina';

    protected $fillable = [
        'Direccion_Pais_Id1',
        'Direccion_Provincia_Id1',
        'Direccion_Partido_Id1',
        'Direccion_Localidad_Id1',
        'Direccion_Ciudad_Id1',
        'Direccion_Barrio_Id1',
        'Direccion_SubBarrio_Id1',
        'Direccion_Calle_Id1',
        'Direccion_Nombrecalle',
        'Direccion_Numero',
        'Direccion_Piso',
        'Direccion_Departamento',
        'Direccion_Coordenadas_Latitud',
        'Direccion_Coordenadas_Longitud',
        'Antiguedad',
        'fk_Orientacion',
        'fk_Estado',
        'CantidadBanos',
        'fk_TipoBano',
        'SuperficiePlanta',
        'cupada',
        'MontoExpensas',
        'Reciclado',
        'DepartamentosPorPiso',
        'AptoProfesional',
        'SuperficieDeposito',
        'SuperficieOficina',
        'fk_TipoAscensor',
        'fk_TipoPiso',
        'fk_TipoBalcon',
        'CantidadAmbientes',
        'CantidadCocheras',
        'Instalaciones_AireAcondicionadoCentral',
        'Instalaciones_AireAcondicionadoIndividual',
        'Instalaciones_AireCaliente',
        'Instalaciones_Ascensor',
        'Instalaciones_Cableado',
        'Instalaciones_Caldera',
        'Instalaciones_Calefaccion',
        'Instalaciones_Conmutador',
        'Instalaciones_EspacioParaVehiculo',
        'Instalaciones_Gimnasio',
        'Instalaciones_GrupoElectrogeno',
        'Instalaciones_JuegosParaChicos',
        'Instalaciones_Laundry',
        'Instalaciones_LosaRadiante',
        'Instalaciones_MovilidadReducida',
        'Instalaciones_Pavimento',
        'Instalaciones_Pileta',
        'Instalaciones_Pisoductos',
        'Instalaciones_Radiadores',
        'Instalaciones_SalonDeFiestas',
        'Instalaciones_Sauna',
        'Instalaciones_Telefono',
        'Instalaciones_Termotanque',
        'Servicios_ABL',
        'Servicios_AguaCorriente',
        'Servicios_Bar',
        'Servicios_Calefaccion',
        'Servicios_Cocina',
        'Servicios_Conmutador',
        'Servicios_Electricidad',
        'Servicios_GasEnvasado',
        'Servicios_GasNatural',
        'Servicios_Internet',
        'Servicios_Lavanderia',
        'Servicios_Refrigeracion',
        'Servicios_Rentas',
        'Servicios_Seguridad',
        'Servicios_Telefono',
        'Servicios_Videocable',
        'Servicios_Vigilancia',
        'Ambientes_Altillo',
        'Ambientes_AnteCocina',
        'Ambientes_Archivo',
        'Ambientes_Azotea',
        'Ambientes_Bano',
        'Ambientes_Baulera',
        'Ambientes_Circulacion',
        'Ambientes_Cochera',
        'Ambientes_Cocina',
        'Ambientes_CuartoDeHerramientas',
        'Ambientes_Deposito',
        'Ambientes_Entrepiso',
        'Ambientes_Garage',
        'Ambientes_Sala',
        'Ambientes_SalonPublico',
        'Ambientes_Terraza',
        'Ambientes_Toilette',
        'Generales_SeguroCaucion', º,
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
    ];


}
