import { isMedidas } from "../datosPorTipoPropiedad";


export const caracteristicasDepartamento = {
    AptoCredito: true,
    LongitudFrente: true,
    LongitudFondo: true,
    SuperficieCubierta: true,
    SuperficieDescubierta: true,
    Antiguedad: true,
    AptoProfesional: true,
    CantidadCocheras: true,
    CocheraOptativa: true,
    fk_Disposicion: true,
    Expensas: true,
    fk_Orientacion: true,
    PropiedadOcupada: true,
    fk_TipoBalcon: true,
    fk_TipoExpensas: true,
    fk_TipoVista: true,
    fk_TipoCosta: true,
    CantidadBanos: true,
    CantidadAmbientes: true,
    CantidadDormitorios: true,
    Generales_PermiteMascotas: true,
    Generales_SeguroCaucion: true,
}
export const arrayAmbientesDepartamento = [
    { label: "Altillo", variableName: "Ambientes_Altillo", isMedidas: isMedidas("Altillo"), medidas: '', selected: false },
    { label: "Antesala", variableName: "Ambientes_Antesala", isMedidas: isMedidas("Antesala"), medidas: '', selected: false },
    { label: "Balcón", variableName: "Ambientes_Balcon", isMedidas: isMedidas("Balcon"), medidas: '', selected: false },
    { label: "Baño", variableName: "Ambientes_Bano", isMedidas: isMedidas("Bano"), medidas: '', selected: false },
    { label: "Bar", variableName: "Ambientes_Bar", isMedidas: isMedidas("Bar"), medidas: '', selected: false },
    { label: "Baulera", variableName: "Ambientes_Baulera", isMedidas: isMedidas("Baulera"), medidas: '', selected: false },
    { label: "Biblioteca", variableName: "Ambientes_Biblioteca", isMedidas: isMedidas("Biblioteca"), medidas: '', selected: false },
    { label: "Circulación", variableName: "Ambientes_Circulacion", isMedidas: isMedidas("Circulacion"), medidas: '', selected: false },
    { label: "Cochera", variableName: "Ambientes_Cochera", isMedidas: isMedidas("Cochera"), medidas: '', selected: false },
    { label: "Cocina", variableName: "Ambientes_Cocina", isMedidas: isMedidas("Cocina"), medidas: '', selected: false },
    { label: "Cocina Comedor", variableName: "Ambientes_CocinaComedor", isMedidas: isMedidas("CocinaComedor"), medidas: '', selected: false },
    { label: "Cocina Kitchinette", variableName: "Ambientes_CocinaKitchinette", isMedidas: isMedidas("CocinaKitchinette"), medidas: '', selected: false },
    { label: "Comedor", variableName: "Ambientes_Comedor", isMedidas: isMedidas("Comedor"), medidas: '', selected: false },
    { label: "Comedor Diario", variableName: "Ambientes_ComedorDiario", isMedidas: isMedidas("ComedorDiario"), medidas: '', selected: false },
    { label: "Cuarto De Planchar", variableName: "Ambientes_CuartoDePlanchar", isMedidas: isMedidas("CuartoDePlanchar"), medidas: '', selected: false },
    { label: "Dependencia", variableName: "Ambientes_Dependencia", isMedidas: isMedidas("Dependencia"), medidas: '', selected: false },
    { label: "Dep. De Servicio", variableName: "Ambientes_DependenciaDeServicio", isMedidas: isMedidas("DependenciaDeServicio"), medidas: '', selected: false },
    { label: "Dormitorio", variableName: "Ambientes_Dormitorio", isMedidas: isMedidas("Dormitorio"), medidas: '', selected: false },
    { label: "Entrepiso", variableName: "Ambientes_Entrepiso", isMedidas: isMedidas("Entrepiso"), medidas: '', selected: false },
    { label: "Escritorio", variableName: "Ambientes_Escritorio", isMedidas: isMedidas("Escritorio"), medidas: '', selected: false },
    { label: "Estudio", variableName: "Ambientes_Estudio", isMedidas: isMedidas("Estudio"), medidas: '', selected: false },
    { label: "Family Room", variableName: "Ambientes_FamilyRoom", isMedidas: isMedidas("FamilyRoom"), medidas: '', selected: false },
    { label: "Hall", variableName: "Ambientes_Hall", isMedidas: isMedidas("Hall"), medidas: '', selected: false },
    { label: "Jardín", variableName: "Ambientes_Jardin", isMedidas: isMedidas("Jardin"), medidas: '', selected: false },
    { label: "Lavadero", variableName: "Ambientes_Lavadero", isMedidas: isMedidas("Lavadero"), medidas: '', selected: false },
    { label: "Living", variableName: "Ambientes_Living", isMedidas: isMedidas("Living"), medidas: '', selected: false },
    { label: "Living Comedor", variableName: "Ambientes_LivingComedor", isMedidas: isMedidas("LivingComedor"), medidas: '', selected: false },
    { label: "Palier", variableName: "Ambientes_Palier", isMedidas: isMedidas("Palier"), medidas: '', selected: false },
    { label: "Patio", variableName: "Ambientes_Patio", isMedidas: isMedidas("Patio"), medidas: '', selected: false },
    { label: "Playroom", variableName: "Ambientes_Playroom", isMedidas: isMedidas("Playroom"), medidas: '', selected: false },
    { label: "Recepción", variableName: "Ambientes_Recepcion", isMedidas: isMedidas("Recepcion"), medidas: '', selected: false },
    { label: "Sótano", variableName: "Ambientes_Sotano", isMedidas: isMedidas("Sotano"), medidas: '', selected: false },
    { label: "Suite", variableName: "Ambientes_Suite", isMedidas: isMedidas("Suite"), medidas: '', selected: false },
    { label: "Terraza", variableName: "Ambientes_Terraza", isMedidas: isMedidas("Terraza"), medidas: '', selected: false },
    { label: "Toilette", variableName: "Ambientes_Toilette", isMedidas: isMedidas("Toilette"), medidas: '', selected: false },
    { label: "Vestidor", variableName: "Ambientes_Vestidor", isMedidas: isMedidas("Vestidor"), medidas: '', selected: false },
]


export const arrayInstalacionesDepartamento = [
    { label: "Agua Caliente", variableName: "Instalaciones_AguaCaliente", selected: false },
    { label: "Agua Caliente Central", variableName: "Instalaciones_AguaCalienteCentral", selected: false },
    { label: "Agua Corriente", variableName: "Instalaciones_AguaCorriente", selected: false },
    { label: "Aire Acond. Individual", variableName: "Instalaciones_AireAcondicionadoIndividual", selected: false },
    { label: "Amoblado", variableName: "Instalaciones_Amoblado", selected: false },
    { label: "Ascensor", variableName: "Instalaciones_Ascensor", selected: false },
    { label: "Ascensores De Servicio", variableName: "Instalaciones_AscensoresDeServicio", selected: false },
    { label: "Ascensores Principales", variableName: "Instalaciones_AscensoresPrincipales", selected: false },
    { label: "Cable", variableName: "Instalaciones_Cable", selected: false },
    { label: "Caja Fuerte", variableName: "Instalaciones_CajaFuerte", selected: false },
    { label: "Caldera", variableName: "Instalaciones_Caldera", selected: false },
    { label: "Calefacción", variableName: "Instalaciones_Calefaccion", selected: false },
    { label: "Cancha Futbol", variableName: "Instalaciones_CanchaFutbol", selected: false },
    { label: "Cancha Tenis", variableName: "Instalaciones_CanchaTenis", selected: false },
    { label: "Desayunador", variableName: "Instalaciones_Desayunador", selected: false },
    { label: "Electricidad", variableName: "Instalaciones_Electricidad", selected: false },
    { label: "Extractor De Aire", variableName: "Instalaciones_ExtractorDeAire", selected: false },
    { label: "Gas Envasado", variableName: "Instalaciones_GasEnvasado", selected: false },
    { label: "Gas Natural", variableName: "Instalaciones_GasNatural", selected: false },
    { label: "Hogar A Leña", variableName: "Instalaciones_HogarALena", selected: false },
    { label: "Instalación Parrilla", variableName: "Instalaciones_InstalacionParrilla", selected: false },
    { label: "Losa Radiante", variableName: "Instalaciones_LosaRadiante", selected: false },
    { label: "Movilidad Reducida", variableName: "Instalaciones_MovilidadReducida", selected: false },
    { label: "Muebles De Cocina", variableName: "Instalaciones_MueblesDeCocina", selected: false },
    { label: "Pavimento", variableName: "Instalaciones_Pavimento", selected: false },
    { label: "Solarium", variableName: "Instalaciones_Solarium", selected: false },
    { label: "Teléfono", variableName: "Instalaciones_Telefono", selected: false },
    { label: "Termotanque", variableName: "Instalaciones_Termotanque", selected: false },
];


export const arrayServiciosDepartamento = [
    { label: "ABL", variableName: "Servicios_ABL", selected: false },
    { label: "Agua Corriente", variableName: "Servicios_AguaCorriente", selected: false },
    { label: "Calefaccion", variableName: "Servicios_Calefaccion", selected: false },
    { label: "Electricidad", variableName: "Servicios_Electricidad", selected: false },
    { label: "Gas Envasado", variableName: "Servicios_GasEnvasado", selected: false },
    { label: "Gas Natural", variableName: "Servicios_GasNatural", selected: false },
    { label: "Internet", variableName: "Servicios_Internet", selected: false },
    { label: "Limpieza", variableName: "Servicios_Limpieza", selected: false },
    { label: "Refrigeración", variableName: "Servicios_Refrigeracion", selected: false },
    { label: "Rentas", variableName: "Servicios_Rentas", selected: false },
    { label: "Ropa Cama", variableName: "Servicios_RopaCama", selected: false },
    { label: "Seguridad", variableName: "Servicios_Seguridad", selected: false },
    { label: "Teléfono", variableName: "Servicios_Telefono", selected: false },
    { label: "Toallas", variableName: "Servicios_Toallas", selected: false },
    { label: "Videocable", variableName: "Servicios_Videocable", selected: false },
    { label: "Vigilancia", variableName: "Servicios_Vigilancia", selected: false },
];

export const arrayEdificioServiciosDepartamento = [
    { label: "ABL", variableName: "Edificio_Servicios_ABL", selected: false },
    { label: "Agua Corriente", variableName: "Edificio_Servicios_AguaCorriente", selected: false },
    { label: "Bar", variableName: "Edificio_Servicios_Bar", selected: false },
    { label: "Calefacción", variableName: "Edificio_Servicios_Calefaccion", selected: false },
    { label: "Cocina", variableName: "Edificio_Servicios_Cocina", selected: false },
    { label: "Conmutador", variableName: "Edificio_Servicios_Conmutador", selected: false },
    { label: "Electricidad", variableName: "Edificio_Servicios_Electricidad", selected: false },
    { label: "Gas Envasado", variableName: "Edificio_Servicios_GasEnvasado", selected: false },
    { label: "Gas Natural", variableName: "Edificio_Servicios_GasNatural", selected: false },
    { label: "Internet", variableName: "Edificio_Servicios_Internet", selected: false },
    { label: "Lavandería", variableName: "Edificio_Servicios_Lavanderia", selected: false },
    { label: "Refrigeración", variableName: "Edificio_Servicios_Refrigeracion", selected: false },
    { label: "Rentas", variableName: "Edificio_Servicios_Rentas", selected: false },
    { label: "Seguridad", variableName: "Edificio_Servicios_Seguridad", selected: false },
    { label: "Teléfono", variableName: "Edificio_Servicios_Telefono", selected: false },
    { label: "Videocable", variableName: "Edificio_Servicios_Videocable", selected: false },
    { label: "Vigilancia", variableName: "Edificio_Servicios_Vigilancia", selected: false },
]
