export const caracteristicasGalpon = {
    SuperficieCubierta: true,
    SuperficieDescubierta: true,
    SuperficiePlaya: true,
    LongitudFrente: true,
    LongitudFondo: true,
    Antiguedad: true,
    CantidadBanos: true,
    CantidadOficinas: true,
    fk_TipoTechoIndustrial: true,
    fk_TipoPorton: true,
    GeneradorPropio: true,
    fk_TipoCalefaccion: true,
    AnchoEntrada: true,
    AltoEntrada: true,
    CantidadColumnas: true,
    CantidadNaves: true,
    PropiedadOcupada: true,
    CantidadPlantas: true,
    AlturaTecho: true,
    FOT: true,
    Generales_SeguroCaucion: true,
}


export const arrayInstalacionesGalpon = [

    { label: "Agua Corriente", variableName: "Instalaciones_AguaCorriente", selected: false },
    { label: "Aire Acondicionado Central", variableName: "Instalaciones_AireAcondicionadoCentral", selected: false },
    { label: "Aire Acondicionado Individual", variableName: "Instalaciones_AireAcondicionadoIndividual", selected: false },
    { label: "Balanza", variableName: "Instalaciones_Balanza", selected: false },
    { label: "Bombeador", variableName: "Instalaciones_Bombeador", selected: false },
    { label: "Caldera Individual", variableName: "Instalaciones_Caldera", selected: false },
    { label: "Electricidad", variableName: "Instalaciones_Electricidad", selected: false },
    { label: "Fuerza Motriz", variableName: "Instalaciones_FuerzaMotriz", selected: false },
    { label: "Gas Envasado", variableName: "Instalaciones_GasEnvasado", selected: false },
    { label: "Gas Industrial", variableName: "Instalaciones_GasIndustrial", selected: false },
    { label: "Gas Natural", variableName: "Instalaciones_GasNatural", selected: false },
    { label: "Grua", variableName: "Instalaciones_Grua", selected: false },
    { label: "Grupo Electrógeno", variableName: "Instalaciones_GrupoElectrogeno", selected: false },
    { label: "Instalación Parrilla", variableName: "Instalaciones_InstalacionParrilla", selected: false },
    { label: "Luz Eléctrica", variableName: "Instalaciones_LuzElectrica", selected: false },
    { label: "Montacarga", variableName: "Instalaciones_Montacarga", selected: false },
    { label: "Motores", variableName: "Instalaciones_Motores", selected: false },
    { label: "Portón", variableName: "Instalaciones_Porton", selected: false },
    { label: "Piso Radiante Individual", variableName: "piso_Radiante_Individual", selected: false },
    { label: "Piso Radiante Central", variableName: "piso_Radiante_Central", selected: false },
    { label: "Hidromasaje", variableName: "hidromasaje", selected: false },
    { label: "Radiadores", variableName: "Instalaciones_Radiadores", selected: false },
    { label: "Calefón", variableName: "calefon", selected: false },
    { label: "Tanque De Agua", variableName: "Instalaciones_TanqueDeAgua", selected: false },
    { label: "Tanque De Incendio", variableName: "Instalaciones_TanqueDeIncendio", selected: false },
    { label: "Teléfono", variableName: "Instalaciones_Telefono", selected: false },
    { label: "Termotanque", variableName: "Instalaciones_Termotanque", selected: false },
    { label: "Vivienda", variableName: "Instalaciones_Vivienda", selected: false },
];

export const arrayServiciosGalpon = [
    //Servicios
    { label: "ABL", variableName: "Servicios_ABL", selected: false },
    { label: "Agua Corriente", variableName: "Servicios_AguaCorriente", selected: false },
    { label: "Electricidad", variableName: "Servicios_Electricidad", selected: false },
    { label: "Gas Envasado", variableName: "Servicios_GasEnvasado", selected: false },
    { label: "Gas Natural", variableName: "Servicios_GasNatural", selected: false },
    { label: "Internet", variableName: "Servicios_Internet", selected: false },
    { label: "Refrigeración", variableName: "Servicios_Refrigeracion", selected: false },
    { label: "Rentas", variableName: "Servicios_Rentas", selected: false },
    { label: "Seguridad", variableName: "Servicios_Seguridad", selected: false },
    { label: "Teléfono", variableName: "Servicios_Telefono", selected: false },
    { label: "Videocable", variableName: "Servicios_Videocable", selected: false },
    { label: "Vigilancia", variableName: "Servicios_Vigilancia", selected: false },
]