export const caracteristicasGalpon = [
            { label: "Superficie Cubierta", variableName: "SuperficieCubierta",selected: false, value:""},
            { label: "Superficie Descubierta", variableName: "SuperficieDescubierta",selected: false, value:""},
            { label: "Superficie Playa", variableName: "SuperficiePlaya",selected: false, value:""},
            { label: "Longitud Frente", variableName: "LongitudFrente",selected: false, value:""},
            { label: "Longitud Fondo", variableName: "LongitudFondo",selected: false, value:""},
            { label: "Antiguedad", variableName: "Antiguedad",selected: false, value:""},
            { label: "Cantidad Baño", variableName: "CantidadBanos",selected: false, value:""},
            { label: "Cantidad Oficinas", variableName: "CantidadOficinas",selected: false, value:""},
            { label: "Tipo Techo Industrial", variableName: "tipo_techo_industrial",selected: false, value:""},
            { label: "Tipo Porton", variableName: "tipo_porton",selected: false, value:""},
            { label: "Generador Propio", variableName: "GeneradorPropio",selected: false, value:""},
            { label: "Tipo Calefaccion", variableName: "tipo_calefaccion",selected: false, value:""},
            { label: "Ancho Entrada", variableName: "AnchoEntrada",selected: false, value:""},
            { label: "Alto Entrada", variableName: "AltoEntrada",selected: false, value:""},
            { label: "Cantidad Columnas", variableName: "CantidadColumnas",selected: false, value:""},
            { label: "Cantidad Naves", variableName: "CantidadNaves",selected: false, value:""},
            { label: "Propiedad Ocupada", variableName: "PropiedadOcupada",selected: false, value:""},
            { label: "Cantidad Plantas", variableName: "CantidadPlantas",selected: false, value:""},
            { label: "Altura Techo", variableName: "AlturaTecho",selected: false, value:""},
            { label: "FOT", variableName: "FOT",selected: false, value:""},
            { label: "Generales SeguroCaucion", variableName: "Generales_SeguroCaucion",selected: false, value:""},
]


export const arrayInstalacionesGalpon = [

    { label: "Agua Corriente", variableName: "Instalaciones_AguaCorriente", selected: false },
    { label: "Aire Acondicionado Central", variableName: "Instalaciones_AireAcondicionadoCentral", selected: false },
    { label: "Aire Acondicionado Individual", variableName: "Instalaciones_AireAcondicionadoIndividual", selected: false },
    { label: "Balanza", variableName: "Instalaciones_Balanza", selected: false },
    { label: "Bombeador", variableName: "Instalaciones_Bombeador", selected: false },
    { label: "Caldera", variableName: "Instalaciones_Caldera", selected: false },
    { label: "Electricidad", variableName: "Instalaciones_Electricidad", selected: false },
    { label: "Fuerza Motriz", variableName: "Instalaciones_FuerzaMotriz", selected: false },
    { label: "Gas Envasado", variableName: "Instalaciones_GasEnvasado", selected: false },
    { label: "Gas Industrial", variableName: "Instalaciones_GasIndustrial", selected: false },
    { label: "Gas Natural", variableName: "Instalaciones_GasNatural", selected: false },
    { label: "Grua", variableName: "Instalaciones_Grua", selected: false },
    { label: "Grupo Electrógeno", variableName: "Instalaciones_GrupoElectrogeno", selected: false },
    { label: "Instalación Parrilla", variableName: "Instalaciones_InstalacionParrilla", selected: false },
    { label: "Luz Eléctrica", variableName: "Instalaciones_LuzElectrica", selected: false },
    { label: "Montacarga", variableName: "Instalaciones_Montacarga", selected: false },
    { label: "Motores", variableName: "Instalaciones_Motores", selected: false },
    { label: "Portón", variableName: "Instalaciones_Porton", selected: false },
    { label: "Tanque De Agua", variableName: "Instalaciones_TanqueDeAgua", selected: false },
    { label: "Tanque De Incendio", variableName: "Instalaciones_TanqueDeIncendio", selected: false },
    { label: "Teléfono", variableName: "Instalaciones_Telefono", selected: false },
    { label: "Termotanque", variableName: "Instalaciones_Termotanque", selected: false },
    { label: "Vivienda", variableName: "Instalaciones_Vivienda", selected: false },
];

export const arrayServiciosGalpon = [
    //Servicios
    { label: "ABL", variableName: "Servicios_ABL", selected: false },
    { label: "Agua Corriente", variableName: "Servicios_AguaCorriente", selected: false },
    { label: "Electricidad", variableName: "Servicios_Electricidad", selected: false },
    { label: "Gas Envasado", variableName: "Servicios_GasEnvasado", selected: false },
    { label: "Gas Natural", variableName: "Servicios_GasNatural", selected: false },
    { label: "Internet", variableName: "Servicios_Internet", selected: false },
    { label: "Refrigeración", variableName: "Servicios_Refrigeracion", selected: false },
    { label: "Rentas", variableName: "Servicios_Rentas", selected: false },
    { label: "Seguridad", variableName: "Servicios_Seguridad", selected: false },
    { label: "Teléfono", variableName: "Servicios_Telefono", selected: false },
    { label: "Videocable", variableName: "Servicios_Videocable", selected: false },
    { label: "Vigilancia", variableName: "Servicios_Vigilancia", selected: false },
]