export const caracteristicasTerreno = [
                  { label:"SuperficieTotal", variableName: "SuperficieTotal",selected: false, value:""},
                  { label:"SuperficieConstruible", variableName: "SuperficieConstruible",selected: false, value:""},
                  { label:"PropiedadOcupada", variableName: "PropiedadOcupada",selected: false, value:""},
                  { label:"Demolicion", variableName: "Demolicion",selected: false, value:""},
                  { label:"FondoIrregular", variableName: "FondoIrregular",selected: false, value:""},
                  { label:"FrenteIrregular", variableName: "FrenteIrregular",selected: false, value:""},
                  { label:"LateralDerechoIrregular", variableName: "LateralDerechoIrregular",selected: false, value:""},
                  { label:"LateralIzquierdoIrregular", variableName: "LateralIzquierdoIrregular",selected: false, value:""},
                  { label:"MedidaLinealDerecha", variableName: "MedidaLinealDerecha",selected: false, value:""},
                  { label:"MedidaLinealIzquierda", variableName: "MedidaLinealIzquierda",selected: false, value:""},
                  { label:"LongitudFrente", variableName: "LongitudFrente",selected: false, value:""},
                  { label:"LongitudFondo", variableName: "LongitudFondo",selected: false, value:""},
                  { label:"fk_TipoCosta", variableName: "tipo_costa",selected: false, value:""},
                  { label:"fk_TipoPendiente", variableName: "tipo_pendiente",selected: false, value:""},
                  { label:"fk_TipoVista", variableName: "tipo_vista",selected: false, value:""},
                  { label:"FOT", variableName: "FOT",selected: false, value:""},
                  { label:"Zonificacion", variableName: "Zonificacion",selected: false, value:""},
                  { label:"Generales_SeguroCaucion", variableName: "Generales_SeguroCaucion",selected: false, value:""},
]

export const arrayInstalacionesTerreno = [

    { label: "Agua Cloaca", variableName: "Instalaciones_AguaCloaca", selected: false },
    { label: "Agua Corriente", variableName: "Instalaciones_AguaCorriente", selected: false },
    { label: "Agua Pozo", variableName: "Instalaciones_AguaPozo", selected: false },
    { label: "Alambrados", variableName: "Instalaciones_Alambrados", selected: false },
    { label: "Arboleda", variableName: "Instalaciones_Arboleda", selected: false },
    { label: "Bebedero", variableName: "Instalaciones_Bebedero", selected: false },
    { label: "Bretes", variableName: "Instalaciones_Bretes", selected: false },
    { label: "Corral", variableName: "Instalaciones_Corral", selected: false },
    { label: "Electricidad", variableName: "Instalaciones_Electricidad", selected: false },
    { label: "Estacada", variableName: "Instalaciones_Estacada", selected: false },
    { label: "Forestación", variableName: "Instalaciones_Forestacion", selected: false },
    { label: "Fosas", variableName: "Instalaciones_Fosas", selected: false },
    { label: "Haras", variableName: "Instalaciones_Haras", selected: false },
    { label: "Luz Eléctrica", variableName: "Instalaciones_LuzElectrica", selected: false },
    { label: "Mangas", variableName: "Instalaciones_Mangas", selected: false },
    { label: "Molino", variableName: "Instalaciones_Molino", selected: false },
    { label: "Pavimento", variableName: "Instalaciones_Pavimento", selected: false },
    { label: "Potrero", variableName: "Instalaciones_Potrero", selected: false },
    { label: "Tambo", variableName: "Instalaciones_Tambo", selected: false },
    { label: "Vivienda", variableName: "Instalaciones_Vivienda", selected: false },
];

export const arrayServiciosTerreno = [
    //Servicios
    { label: "ABL", variableName: "Servicios_ABL", selected: false },
    { label: "Agua Corriente", variableName: "Servicios_AguaCorriente", selected: false },
    { label: "Electricidad", variableName: "Servicios_Electricidad", selected: false },
    { label: "Gas Envasado", variableName: "Servicios_GasEnvasado", selected: false },
    { label: "Gas Natural", variableName: "Servicios_GasNatural", selected: false },
    { label: "Rentas", variableName: "Servicios_Rentas", selected: false },
    { label: "Teléfono", variableName: "Servicios_Telefono", selected: false },
]
